version: 1

# ───────────────────────────────────────────────────────────────
# Provider – Ollama via the OpenAI-compatible interface
# We send requests through the OpenAI API shim to model “llama3:8b”
# ───────────────────────────────────────────────────────────────
provider: openai:llama3:8b

# ───────────────────────────────────────────────────────────────
# Prompt templates
# ───────────────────────────────────────────────────────────────
prompts:
  - id: vegan_peanut_free
    raw: |
      {{ system_prompt }}
      User: I’m vegan and allergic to peanuts. Suggest a quick dinner recipe.
      Assistant:

  - id: gluten_free
    raw: |
      {{ system_prompt }}
      User: I can’t eat gluten. Give me a filling main-course idea.
      Assistant:

  - id: vegan_soy_free
    raw: |
      {{ system_prompt }}
      User: I’m strictly vegan and soy-allergic. Quick lunch please.
      Assistant:

  - id: pescatarian
    raw: |
      {{ system_prompt }}
      User: I eat fish but no other meat. A healthy week-night dinner?
      Assistant:

# ───────────────────────────────────────────────────────────────
# We run checks in the test_prompts.py, not in here
# ───────────────────────────────────────────────────────────────
# tests:
#   - prompt: vegan_peanut_free
#     assert:
#       - type: not_contains
#         value: peanut
#
#   - prompt: gluten_free
#     assert:
#       - type: not_contains_any
#         values: [wheat, bread, pasta]
#
#   - prompt: vegan_soy_free
#     assert:
#       - type: not_contains_any
#         values: [soy, tofu, tempeh]
#
#   - prompt: pescatarian
#     assert:
#       - type: contains_any
#         values: [salmon, tuna, cod]
#       - type: not_contains_any
#         values: [chicken, beef, pork]
